# Generated by Django 5.1.5 on 2025-02-10 06:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'statuses',
            },
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.branch')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Marquee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('is_cut_off', models.BooleanField(default=False)),
                ('quota', models.PositiveIntegerField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.category')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, max_length=50, null=True)),
                ('queue_code', models.CharField(blank=True, max_length=10, null=True)),
                ('applicant_name', models.CharField(max_length=50)),
                ('no_applicant', models.PositiveIntegerField(blank=True, null=True)),
                ('applicant_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_senior_pwd', models.BooleanField(default=False)),
                ('queue_no', models.PositiveIntegerField()),
                ('coordinator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('is_called', models.BooleanField(default=False)),
                ('is_priority', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.category')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.service')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queues.status')),
                ('window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='queues.window')),
            ],
        ),
    ]
