# Generated by Django 5.1.1 on 2024-10-08 17:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("queues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 10, 8, 17, 9, 13, 109978, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="MarkQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                (
                    "branch_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="queues.branch"
                    ),
                ),
            ],
        ),
    ]
