# Generated by Django 5.1.1 on 2024-10-08 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobile",
            name="printer_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="queues.printer",
            ),
        ),
    ]
