# Generated by Django 5.1.3 on 2024-11-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_auto_20241122_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='is_senior_pwd',
            field=models.BooleanField(default=False),
        ),
    ]
