# Generated by Django 5.1.1 on 2024-10-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("queues", "0003_alter_queue_window_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
