# Generated by Django 5.1.3 on 2024-12-30 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0003_queue_is_senior_pwd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
