# Generated by Django 5.1.3 on 2024-12-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0004_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='branch_id',
            new_name='branch',
        ),
    ]
