# Generated by Django 5.1.3 on 2025-01-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0005_rename_branch_id_queue_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='category_id',
            new_name='category',
        ),
    ]
