# Generated by Django 5.1.3 on 2025-01-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0006_rename_category_id_queue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
