# Generated by Django 5.1.3 on 2025-01-04 04:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0007_alter_queue_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
