# Generated by Django 5.1.3 on 2025-01-04 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0008_alter_queue_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='service_id',
            new_name='service',
        ),
    ]
