# Generated by Django 5.1.3 on 2025-01-04 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0009_rename_service_id_queue_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='window_id',
            new_name='window',
        ),
    ]
