# Generated by Django 5.1.3 on 2025-01-04 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0010_rename_window_id_queue_window'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='status_id',
            new_name='status',
        ),
    ]
