# Generated by Django 5.1.3 on 2025-01-05 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0012_rename_category_id_servicetype_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_type_id',
            new_name='service_type',
        ),
    ]
