# Generated by Django 5.1.3 on 2025-01-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0013_rename_category_id_service_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='branch_id',
            new_name='branch',
        ),
    ]
