# Generated by Django 5.1.3 on 2025-01-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0015_rename_branch_id_printer_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markqueue',
            old_name='branch_id',
            new_name='branch',
        ),
    ]
