# ADD THE FOLLOWING TO THE MIGRATIONS 

# 1st Step (command)
# python manage.py makemigrations --empty yourappname


# 2nd Step (copy-paste)
# Generated by Django 5.1.1 on 2024-10-15 06:46

# from django.db import migrations
# from queues.seeds import default_data

# class Migration(migrations.Migration):

#     dependencies = [
#         ("queues", "0001_initial"),
#     ]
    
#     operations = [
#         migrations.RunPython(data)
#         for data in default_data
#     ]


from .branches import create_default_branches
from .categories import create_default_categories
from .marquees import create_default_marquees
from .services import create_default_services
from .statuses import create_default_statuses
from .windows import create_default_windows


default_data = [
    create_default_branches,
    create_default_categories,
    create_default_marquees,
    create_default_services,
    create_default_statuses,
    create_default_windows
]