# Branches
MAIN_OFFICE_ID = 1
MOA_ID = 2
MEGAMALL_ID = 3
NORTH_EDSA_ID = 4
FAIRVIEW_ID = 5
SOUTHMALL_ID = 6
CLARK_ID = 7
CEBU_ID = 8
DAVAO_ID = 9

# Category Names
JAPAN_VISA = "JAPAN VISA"
KOREA_VISA = "KOREA VISA"
TICKET = "TICKET"
PASSPORT = "PASSPORT"
TOUR_PACKAGE = "TOUR PACKAGE"
OTHER_VISA = "OTHER VISA"
OTHER_SERVICES = "OTHER SERVICES"


# Category IDs
JAPAN_VISA_MAIN_OFFICE_ID = 1
KOREA_VISA_MAIN_OFFICE_ID = 2
TICKET_MAIN_OFFICE_ID = 3
PASSPORT_MAIN_OFFICE_ID = 4
TOUR_PACKAGE_MAIN_OFFICE_ID = 5
OTHER_VISA_MAIN_OFFICE_ID = 6
OTHER_SERVICES_MAIN_OFFICE_ID = 7


JAPAN_VISA_MOA_ID = 8
KOREA_VISA_MOA_ID = 9
TICKET_MOA_ID = 10
PASSPORT_MOA_ID = 11


JAPAN_VISA_MEGAMALL_ID = 12
KOREA_VISA_MEGAMALL_ID = 13
TICKET_MEGAMALL_ID = 14
PASSPORT_MEGAMALL_ID = 15


JAPAN_VISA_NORTH_EDSA_ID = 16
KOREA_VISA_NORTH_EDSA_ID = 17
TICKET_NORTH_EDSA_ID = 18
PASSPORT_NORTH_EDSA_ID = 19


JAPAN_VISA_FAIRVIEW_ID = 20
KOREA_VISA_FAIRVIEW_ID = 21
TICKET_FAIRVIEW_ID = 22
PASSPORT_FAIRVIEW_ID = 23


JAPAN_VISA_SOUTHMALL_ID = 24
KOREA_VISA_SOUTHMALL_ID = 25
TICKET_SOUTHMALL_ID = 26
PASSPORT_SOUTHMALL_ID = 27


JAPAN_VISA_CLARK_ID = 28
KOREA_VISA_CLARK_ID = 29
TICKET_CLARK_ID = 30
PASSPORT_CLARK_ID = 31


JAPAN_VISA_CEBU_ID = 32
KOREA_VISA_CEBU_ID = 33
TICKET_CEBU_ID = 34
PASSPORT_CEBU_ID = 35


JAPAN_VISA_DAVAO_ID = 36
KOREA_VISA_DAVAO_ID = 37
TICKET_DAVAO_ID = 38
PASSPORT_DAVAO_ID = 39