# Branches
MAIN_OFFICE_ID = 1
MOA_ID = 2
MEGAMALL_ID = 3
NORTH_EDSA_ID = 4
FAIRVIEW_ID = 5
SOUTHMALL_ID = 6
CLARK_ID = 7
CEBU_ID = 8
DAVAO_ID = 9

# Categories
JAPAN_VISA_ID = 1
KOREA_VISA_ID = 2
TICKET_ID = 3
CLAIM_PASSPORT_ID = 4
# VISA_CONSULTATION_ID = 5
# ADD_ONS_ID = 6
# OTHERS_ID = 7