# Branches
MAIN_OFFICE_ID = 1
MOA_ID = 2
NORTH_EDSA_ID = 3
MEGAMALL_ID = 4
FAIRVIEW_ID = 5
SOUTHMALL_ID = 6
CLARK_ID = 7
CEBU_ID = 8
DAVAO_ID = 9


# Category Names
JAPAN_VISA = "JAPAN VISA"
KOREA_VISA = "KOREA VISA"
CHINA_VISA = "CHINA VISA"
TICKET = "TICKET"
PASSPORT = "PASSPORT"
TOUR_PACKAGE = "TOUR PACKAGE"
OTHER_VISA = "OTHER VISA"
OTHERS = "OTHERS"

# ------------------------ CATEGORY ID --------------------------- #

# Category IDs
JAPAN_VISA_ID = 1
KOREA_VISA_ID = 2
CHINA_VISA_ID = 3
TICKET_ID = 4
PASSPORT_ID = 5
TOUR_PACKAGE_ID = 6
OTHER_VISA_ID = 7
OTHERS_ID = 8